### ISSUE TITLE
"Initial" when parsing value without unit

### ISSUE THREAD

**Issue by tomcikp** [AngleSharp/AngleSharp.Css#18] opened 2019-02-11 20:10 UTC
Thanks for creating this great project.
I'm trying to use it to parse css styles inside SVG files. It works greate, but I have a problem with units.
In CSS inside SVG units are not required. For example: _stroke-width: 2;_ is correct. When I try to parse something without unit I get CssProperty with "initial" value insted of 2 (for example).
Is there any way to get a valid value instead of "initial"?

Below is sample code:

```cs
string svgStyle = "rect { fill: red; stroke: blue; stroke-width: 3 }";
CssParser cssParser = new CssParser(new CssParserOptions()
            {
                IsIncludingUnknownDeclarations = true,
                IsIncludingUnknownRules = true,
                IsToleratingInvalidSelectors = true,
            });
ICssStyleSheet sheet = cssParser.ParseStyleSheet(svgStyle);
```

**Comment by FlorianRappl** [comment] 2019-02-11 21:16
There are a few declarations that accept "unit-less" lengths (for CSS "backwards-compatibility"). AngleSharp.Css knows about some of them. In all other cases there will be a problem, however, you can either override this behavior by rolling out your own declaration / `IValueConverter` (replacing the existing one - if there is one) or you can just ignore such invalid values. However, the latter case will not lead to the CSSOM for values - in fact all values will be considered raw values then (i.e., only their text will be "copied" as is - no further introspection possible).

Now, in this case you mentioned I think the value converter from AngleSharp *is wrong*. This is a bug. The `stroke-width` declaration *should* also accept a number.

I will mark this as a bug (with remark as stated above - how to handle such cases -- especially if its not a bug or you just want *your* behavior).

Please bring up more of these cases - CSS is "huge" and I for sure did forget many cases / implemented them wrong. Sorry for the inconvenience! 

HTH!

**Comment by FlorianRappl** [comment] 2019-05-05 21:49
Landed in `devel`.

**Closed by FlorianRappl** 2019-05-05 21:49 UTC
Labels: bug, converter, declaration
