### ISSUE TITLE
External CSS not working from <link>

### ISSUE THREAD

**Issue by cyraid** [AngleSharp/AngleSharp.Css#140] opened 2023-04-19 07:16 UTC
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ ] Are you running the latest version of AngleSharp? (of AngleSharp.Css yes, but since it only accepts certain versions of AngleSharp, technically no, not of AngleSharp, but yes of AngleSharp.Css)
- [ ] Did you check the FAQs to see if that helps you? (am not aware of an AngleSharp.Css FAQ)
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

## Description

```c#

    var config = Configuration.Default
      .WithRenderDevice(
        new DefaultRenderDevice {
          DeviceWidth = 1920,
          DeviceHeight = 1080
        })
      .WithDefaultLoader(
        new LoaderOptions() {
          IsNavigationDisabled = true,
          IsResourceLoadingEnabled = true
        })
      .WithCss();

    var context = BrowsingContext.New(config);
    var doc = await context.OpenAsync(req => req.Content(@"""
      <html>
        <head><link href=""https://some/tested/url.css"" rel=""stylesheet""></head>
        <body><label>HI</label></body>
      </html>
    """));

    /*var style = doc.CreateElement<IHtmlStyleElement>();
    style.TextContent = File.ReadAllText("some/actual/file.css");

    doc.Head?.AppendElement(style);*/

    var window = doc.DefaultView;
    var tree = window.Render();
    var label = tree.Find(doc.QuerySelector("label"));

    await label.DownloadResources();

    Console.WriteLine($"min-width: {window.GetComputedStyle(label.Ref as HtmlElement).GetMinWidth()}");

```

The css file has:

```css
label, .test {
  min-width: 50px;
  border: 1px solid green;
}
```

If you uncomment the adding IHtmlStyleElement, it will work (injecting style directly), but when using the `<link>` it won't get processed.

## Steps to Reproduce

Use code above.

**Expected behavior:** GetMinWidth() should return "50px" like it does when I add an IHtmlStyleElement directly.

**Actual behavior:** GetMinWidth() returns ""

**Environment details:** Windows 11, .NET 7

**Comment by FlorianRappl** [comment] 2023-06-15 16:40
I think this is a duplicate of #133.

I've added a test to validate that implementation and with the next preview / 1.0.0 this just works fine.

**Closed as completed by FlorianRappl** 2023-06-15 16:40 UTC
Labels: bug
