### ISSUE TITLE
Error in HTML after upgrade to 0.10

### ISSUE THREAD

**Issue by jogibear9988** [AngleSharp/AngleSharp.Css#16] opened 2019-01-21 15:59 UTC
I use following Code:

                        element = CreateElement("button", htmlDocument);
                        ((IHtmlElement) element).GetStyle().SetPointerEvents("auto");
                        ((IHtmlElement) element).GetStyle().SetBorderWidth("1px");
                        ((IHtmlElement) element).GetStyle().SetBorderStyle("solid");
                        ((IHtmlElement) element).GetStyle().SetBorderColor("black");

wich creates following HTML:

         <button style="pointer-events: auto;border-width: 1px;border-top: solid rgba(0, 0, 0, 1);border-right: solid rgba(0, 0, 0, 1);border-bottom: solid rgba(0, 0, 0, 1);border-left: solid rgba(0, 0, 0, 1);"</button>

wich is wrong in Chrome, cause then bordersize is 3px and not 1px

**Comment by jogibear9988** [comment] 2019-01-22 12:22
also it would be nice if the generated css would be smaller (when all borders are the same, they could be combined)

**Comment by jogibear9988** [comment] 2019-01-22 12:30
is there anything I could help to get this fixed?

**Comment by FlorianRappl** [comment] 2019-01-22 13:08
Sure - contribute directly via making the required changes to the source code. There are two locations for this:

1. Generically the recombination algorithms (but I think its mostly non-generic, so this could be also the wrong lead); look at the IValueAggregator and extension methods for it. Specifically the ones used from the `CssStyleDeclaration`
2. The specific value aggregators. Usually they are in the static declaration classes (we have one for each declaration). The ones for the shorthands also specify an `IValueAggregator` instance instead of just a `IValueConverter`.

Sorry that this seems to be quite high-level. I will try to break it down a little bit later, but truth is that the code needs further simplification and improvement in this area. I am hoping to have some time to work in this soon, but currently again busy with some other projects.

I think the whole value model needs further refinement (this is the reason it is not exposed yet).

HTH and let me know if you need further information.

**Comment by jogibear9988** [comment] 2019-01-23 08:39
Maybe as a first step, I disable the aggregation completely? better long corrent styles instead of wrong short ones?

**Comment by jogibear9988** [comment] 2019-01-23 08:39
Is there a way to disable aggregation via code?

**Comment by FlorianRappl** [comment] 2019-01-23 08:42
Not sure if I understand the problem; if you don't want the aggregation then just access the declarations (shorthands are not always expanded, so accessing the declarations gives you for sure the individual ones).

As a result you can just make a simple serialization a la `String.Join("; ", declarations.Select(m => m.CssText))`.

HTH!

**Comment by jogibear9988** [comment] 2019-01-23 10:04
The problem is 

https://github.com/AngleSharp/AngleSharp.Css/blob/master/src/AngleSharp.Css/Dom/Internal/CssStyleDeclaration.cs#L140

shorthandName is "border-width"

then the aggregator here

https://github.com/AngleSharp/AngleSharp.Css/blob/master/src/AngleSharp.Css/Dom/Internal/CssStyleDeclaration.cs#L171

returns a value and you remove them 

https://github.com/AngleSharp/AngleSharp.Css/blob/master/src/AngleSharp.Css/Dom/Internal/CssStyleDeclaration.cs#L178

and so for the next shortHandName = "border-top"

the longhands array is missing the values for "border-width" and the aggregator returns wrong result

**Comment by FlorianRappl** [comment] 2019-01-23 10:05
Yes - PR welcome :)

**Comment by jogibear9988** [comment] 2019-01-23 10:17
if I remove the following line:

 
 
 
 https://github.com/AngleSharp/AngleSharp.Css/blob/master/src/AngleSharp.Css/Dom/Internal/CssStyleDeclaration.cs#L178

the following test

        [Test]
        public void CssBorderTest()
        {
            var context = BrowsingContext.New(Configuration.Default.WithCss());
            var style = new CssStyleDeclaration(context);
            style.SetBorderWidth("1px");
            style.SetBorderStyle("solid");
            style.SetBorderColor("black");
            var css = style.CssText;
        }

will return this

      border-width: 1px; border-top: 1px solid rgba(0, 0, 0, 1); border-right: solid rgba(0, 0, 0, 1); border-bottom: solid rgba(0, 0, 0, 1); border-left: solid rgba(0, 0, 0, 1)

without invalid code is generated

**Comment by jogibear9988** [comment] 2019-01-23 10:34
> Yes - PR welcome :)

atm. I've no good idea how to fix. Only to remove the line, so no incorrect css is generated

**Comment by jogibear9988** [comment] 2019-01-23 12:19
@FlorianRappl should I create a pull req to skip the aggregation? Cause atm I've no good idea how to fix! (because I've not really time to look after).
Or would you leave it as is untile you've time to look after?

**Comment by jogibear9988** [comment] 2019-01-23 18:02
If I change code to this

                    if (shorthands.Any())
                    {
                        var longhands = Declarations.Where(m => !serialized.Contains(m.Name)).ToList();

                        foreach (var shorthandName in shorthands.OrderByDescending(shorthand => _context.GetDeclarationInfo(property).Longhands.Length))
                        {
                            var shorthand = _context.GetDeclarationInfo(shorthandName);
                            var properties = shorthand.Longhands;
                            var values = new ICssValue[properties.Length];
                            var important = 0;
                            var count = 0;
                            var aggregator = shorthand.Converter as IValueAggregator;

                            for (var i = 0; i < values.Length; i++)
                            {
                                var name = properties[i];
                                var longhand = longhands.Where(m => m.Name == name).FirstOrDefault();

                                if (longhand != null)
                                {
                                    count = count + 1;
                                    important = important + (longhand.IsImportant ? 1 : 0);
                                    count++;
                                    values[i] = longhand.RawValue;
                                }
                            }

                            if (count == 0 || aggregator == null)
                                continue;

                            if (important > 0 && important != count)
                                continue;

                            var value = aggregator.Merge(values);

                            if (value != null)
                            {
                                list.Add(CreateNewProperty(shorthandName, value, important != 0));

                                foreach (var name in properties)
                                {
                                    serialized.Add(name);
                                }
                            }
                        }

                        longhands.RemoveAll(m => serialized.Contains(m.Name));
                    }

generated css is okay, but not the shorted, it looks like this:

    border-width: 1px; border-top: 1px solid rgba(0, 0, 0, 1); border-right: solid rgba(0, 0, 0, 1); border-bottom: solid rgba(0, 0, 0, 1); border-left: solid rgba(0, 0, 0, 1)

**Comment by jogibear9988** [comment] 2019-01-27 00:06
I'd like to add smth like

AggregateCssProperties (bool) Property to PrettyStyleFormatter

do you think this would be a good idea?

not sure atm how to implement such aproach, cause don't think you would like it as a property of IStyleFormater

**Comment by jogibear9988** [comment] 2019-02-11 22:17
@FlorianRappl I've not yet had a good idea to solve this ;-(
I've now switched back to 0.9x

**Comment by jogibear9988** [comment] 2019-04-27 10:27
is there amything fix in 0.12 about this issue?

**Comment by FlorianRappl** [comment] 2019-04-27 11:00
> is there anything fixed in 0.12 about this issue?

Current version is 0.10, with 0.11 being the next one to be released. The issue is still open.

**Comment by FlorianRappl** [comment] 2019-05-05 13:25
Landed in `devel`.

**Closed by FlorianRappl** 2019-05-05 13:25 UTC
Labels: bug, cssom, help-wanted

**Comment by jogibear9988** [comment] 2019-05-05 16:31
@FlorianRappl are you sure? I see your commit is about pointer events. But this issue is about that the combine of the css properties does not work.

**Comment by FlorianRappl** [comment] 2019-05-05 17:14
Yes - I am sure. There is a unit test that covers the issue raised here. The other issues w.r.t. recombination still stand and are resolved in the other issues.

**Comment by jogibear9988** [comment] 2019-05-05 17:34
Thanks
